#!/bin/bash

DNAME=$(basename $(pwd))
if [ -n "$1" ]; then
   NAME="$1"
   if [ "$NAME" != "$DNAME" -a  -d ~/projects/"$NAME" ]; then
       cd ~/projects/"$NAME"
   fi
else
    NAME=$(basename $(pwd))
fi

if ! tmux has-session -t "$NAME"; then
  TMUX= tmux new-session -s "$NAME" -d
  if [ -f "project.clj" ]; then
     tmux rename-window -t "$NAME" emacs
     tmux send-keys -t "$NAME" 'emacs project.clj' C-m

     tmux new-window -t "$NAME" -n test-runner
     tmux new-window -t "$NAME" -n misc

     tmux select-window -t "$NAME":0
  fi
fi

if [ -z "$TMUX" ]; then
   tmux attach -t "$NAME"
else
   tmux switch-client -t "$NAME"
fi