#!/bin/bash

if  [[ "$OSTYPE" != "darwin"* ]]; then
    sh bin/linux
else
    sh bin/osx
fi

mkdir -p ~/.lein
if [ ! -L ~/.lein/profiles.clj ]; then
    mkdir -p bak
    mv ~/.lien/profiles.clj bak
    ln -s `pwd`/profiles.clj ~/.lein/profiles.clj
fi

if [ ! -L ~/.lein/user.clj ]; then
    mkdir -p bak
    mv ~/.lein/user.clj bak
    ln -s `pwd`/user.clj ~/.lein/user.clj
fi

if [ ! -L ~/.tmux.conf ]; then
    mkdir -p bak
    mv ~/.tmux.conf bak

    if  [[ "$OSTYPE" != "darwin"* ]]; then
        ln -s `pwd`/tmux.conf.linux ~/.tmux.conf
    else
        ln -s `pwd`/.tmux.conf.osx ~/.tmux.conf
    fi
fi

if [ ! -L ~/.emacs.d ]; then
    mkdir -p bak
    mv ~/.emacs.d bak
    ln -s `pwd`/ ~/.emacs.d
fi

if [ ! -L ~/.ackrc ]; then
    mkdir -p bak
    mv ~/.ackrc bak
    ln -s `pwd`/.ackrc ~/.ackrc
fi

mkdir -p ~/bin
if [ ! -L ~/bin/muxify ]; then
    mkdir -p bak
    mv ~/bin/muxify bak
    ln -s `pwd`/muxify ~/bin/muxify
fi

if [ ! -f `pwd`/user.init.el ];
then
    cp `pwd`/pristine/user.init.el.default `pwd`/user.init.el
fi

git submodule init
git submodule update

vendor/gitutils/submodule-hooks/install.sh `pwd`
